# Employment India Dataset Data Cleaning Project

## Objective

The objective of this project is to clean and prepare the Employment India dataset by applying standard data cleaning techniques using Pandas.

The cleaned dataset will be suitable for data analysis and machine learning tasks.

In [27]:
import pandas as pd
import numpy as np

# Step 1: Load and Inspect Dataset

In this step we load the dataset and perform an initial inspection to understand its structure and contents.

In [ ]:
df = pd.read_csv("Messy_Employment_India_Dataset.csv")

df.head()   # Display the first five rows of the DataFrame

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [29]:
df.tail()   # Display the last five rows of the DataFrame

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [30]:
df.sample(5) # Display a random sample of five rows from the DataFrame

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1923,Employed,18 to 24,NaN,Retail,Mumbai,low,21.0,15000.0,4/7/2028
915,employed,25-34,Diploma,Finance,Bangalore,High,21.0,39700.0,7/4/2025
380,UNEMPLOYED,45-54,high school,Retail,rural,HIGH,NaN,90300.0,1/16/2024
46,Unemployed,25_34,PhD,Retail,suburban,High,17.0,106500.0,2/16/2023
1218,NaN,25_34,Ph.D,Retail,Urban,low,22.0,148400.0,5/3/2026

In [31]:
print("Rows and Columns:", df.shape)  # Print the number of rows and columns in the DataFrame

Rows and Columns: (2000, 9)

# Step 2: Understand Dataset Structure and Data Types

This step helps us understand the structure of the dataset and the data type of each column.

In [34]:
df.info()  # Get a concise summary of the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   str
 1   Age Group             1768 non-null   str
 2   Education             1804 non-null   str
 3   Industry              1799 non-null   str
 4   Location              1787 non-null   str
 5   AI Risk               1716 non-null   str
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   str
dtypes: float64(2), str(7)
memory usage: 140.8 KB

In [ ]:
df.dtypes   # Display the data types of each column in the DataFrame

Status                      str
Age Group                   str
Education                   str
Industry                    str
Location                    str
AI Risk                     str
Years of Experience     float64
Monthly Salary (INR)    float64
Date Recorded               str
dtype: object

In [37]:
df.describe()  # Generate descriptive statistics for the DataFrame, including count, mean, std, min, and max values for numeric columns

       Years of Experience  Monthly Salary (INR)
count           980.000000           1613.000000
mean             15.244898          76886.360818
std               9.103941          41628.008054
min               0.000000           5100.000000
25%               7.000000          40700.000000
50%              16.000000          77200.000000
75%              23.000000         112400.000000
max              30.000000         149900.000000

In [38]:
df.columns  # Display the column names of the DataFrame

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='str')

# Step 3: Identify and Handle Missing Values

Missing values can affect analysis and machine learning models. Therefore they must be identified and handled.

In [39]:
df.isnull().sum()  # Calculate the number of missing values in each column of the DataFrame

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [40]:
(df.isnull().sum() / len(df)) * 100  # Calculate the percentage of missing values in each column of the DataFrame

Status                  13.40
Age Group               11.60
Education                9.80
Industry                10.05
Location                10.65
AI Risk                 14.20
Years of Experience     51.00
Monthly Salary (INR)    19.35
Date Recorded            0.00
dtype: float64

In [41]:
df["Years of Experience"] = df["Years of Experience"].fillna(
    df["Years of Experience"].median()
)  # Fill missing values in the "Years of Experience" column with the median value of that column

In [42]:
df["Monthly Salary (INR)"] = df["Monthly Salary (INR)"].fillna(
    df["Monthly Salary (INR)"].median()
)  # Fill missing values in the "Monthly Salary (INR)" column with the median value of that column

In [43]:
categorical_columns = [
    "Status",
    "Age Group",
    "Education",
    "Industry",
    "Location",
    "AI Risk"
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])  # Fill missing values in categorical columns with the mode (most frequent value) of each column

# Step 4: Remove Duplicate Records

In [44]:
df.duplicated().sum()  # Calculate the number of duplicate rows in the DataFrame

np.int64(0)

In [45]:
df = df.drop_duplicates()  # Remove duplicate rows from the DataFrame

# Step 5: Correct Inconsistent Formatting and Text Values

In [47]:
text_columns = [
    "Status",
    "Age Group",
    "Education",
    "Industry",
    "Location",
    "AI Risk"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()  # Standardize text columns by converting to string, stripping whitespace, and converting to title case

# Step 6: Fix Data Type Issues

In [48]:
df["Date Recorded"] = pd.to_datetime(
    df["Date Recorded"]
) # Convert the "Date Recorded" column to datetime format

In [49]:
df.dtypes  # Display the data types of each column in the DataFrame after cleaning

Status                             str
Age Group                          str
Education                          str
Industry                           str
Location                           str
AI Risk                            str
Years of Experience            float64
Monthly Salary (INR)           float64
Date Recorded           datetime64[us]
dtype: object

# Step 7: Detect and Handle Outliers

In [50]:
df.describe()  # Generate descriptive statistics for the DataFrame, including count, mean, std, min, and max values for numeric columns

       Years of Experience  Monthly Salary (INR)        Date Recorded
count          2000.000000            2000.00000                 2000
mean             15.630000           76947.05000  2025-09-26 12:00:00
min               0.000000            5100.00000  2023-01-01 00:00:00
25%              16.000000           49150.00000  2024-05-14 18:00:00
50%              16.000000           77200.00000  2025-09-26 12:00:00
75%              16.000000          104125.00000  2027-02-08 06:00:00
max              30.000000          149900.00000  2028-06-22 00:00:00
std               6.382278           37382.13816                  NaN

In [ ]:
Q1 = df["Monthly Salary (INR)"].quantile(0.25)

Q3 = df["Monthly Salary (INR)"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - (1.5 * IQR)

upper = Q3 + (1.5 * IQR)    # Calculate the lower and upper bounds for outliers in the "Monthly Salary (INR)" column using the IQR method

In [ ]:
outliers = df[
    (df["Monthly Salary (INR)"] < lower)
    |
    (df["Monthly Salary (INR)"] > upper)
]

outliers      # Display the rows in the DataFrame that are considered outliers based on the "Monthly Salary (INR)" column using the IQR method

Empty DataFrame
Columns: [Status, Age Group, Education, Industry, Location, AI Risk, Years of Experience, Monthly Salary (INR), Date Recorded]
Index: []

In [ ]:
df = df[
    (df["Monthly Salary (INR)"] >= lower)
    &
    (df["Monthly Salary (INR)"] <= upper)
]        # Remove outliers from the DataFrame based on the "Monthly Salary (INR)" column using the IQR method

# Step 8: Rename and Standardize Column Names

In [54]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)  # Standardize column names by stripping whitespace, converting to lowercase, and replacing spaces with underscores

In [55]:
df.columns   # Display the column names of the DataFrame

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_(inr)', 'date_recorded'],
      dtype='str')

# Step 9: Validate and Verify Cleaned Data

In [56]:
df.info() # Get a concise summary of the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   status                2000 non-null   str
 1   age_group             2000 non-null   str
 2   education             2000 non-null   str
 3   industry              2000 non-null   str
 4   location              2000 non-null   str
 5   ai_risk               2000 non-null   str
 6   years_of_experience   2000 non-null   float64
 7   monthly_salary_(inr)  2000 non-null   float64
 8   date_recorded         2000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), str(6)
memory usage: 140.8 KB

In [57]:
df.isnull().sum()  # Calculate the number of missing values in each column of the DataFrame

status                  0
age_group               0
education               0
industry                0
location                0
ai_risk                 0
years_of_experience     0
monthly_salary_(inr)    0
date_recorded           0
dtype: int64

In [58]:
df.duplicated().sum()  # Calculate the number of duplicate rows in the DataFrame

np.int64(0)

In [59]:
df.describe()  # Generate descriptive statistics for the DataFrame, including count, mean, std, min, and max values for numeric columns

       years_of_experience  monthly_salary_(inr)        date_recorded
count          2000.000000            2000.00000                 2000
mean             15.630000           76947.05000  2025-09-26 12:00:00
min               0.000000            5100.00000  2023-01-01 00:00:00
25%              16.000000           49150.00000  2024-05-14 18:00:00
50%              16.000000           77200.00000  2025-09-26 12:00:00
75%              16.000000          104125.00000  2027-02-08 06:00:00
max              30.000000          149900.00000  2028-06-22 00:00:00
std               6.382278           37382.13816                  NaN

In [60]:
df.head() # Display the first five rows of the cleaned DataFrame

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_(inr),date_recorded
0,Employed,25_34,High School,Technology,Urban,High,16.0,40700.0,2023-01-01
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,16.0,17500.0,2023-01-02
2,Employed,25_34,High School,Retail,Delhi,Low,16.0,77600.0,2023-01-03
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,2023-01-04
4,Employed,45-54,Diploma,Fintech,Hyderabad,Low,9.0,19500.0,2023-01-05

# Step 10: Export Final Cleaned Dataset

In [61]:
df.to_csv(
    "cleaned_employment_india.csv",
    index=False
)